eithon:
  UseMarkUpForMessages: 0
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 1

  #
  # Delay (ticks) for title fade in
  TitleFadeInTicks: 20

  #
  # Delay (ticks) for title stay on screen
  TitleStayTicks: 60

  #
  # Delay (ticks) for title fade out
  TitleFadeOutTicks: 20

commands:

  #
  # Parameters: <player name>(%s) <group name>(%s)
  AddGroup_2: perm player %s addgroup %s

  #
  # Parameters: <player name>(%s) <group name>(%s)
  RemoveGroup_2: perm player %s removegroup %s

#
# General messages that are valid over all plugins
#
messages:
  
  # Warning when we expect an entity to be an instance of Player
  # Arguments: <name> (%s)
  ExpectedToBePlayer: Expected %s to be a Player.
  
  # Message sent to the player if he/she hasn't a required permission.
  # Arguments: <permission path> (%s)
  RequiredPermission: You must have permission %s.
  
  # 
  # Arguments: <current world> (%s) <world name list> (%s)
  ExpectedWorlds_2: You are in world %s, but was expected to be in one of [%s].
