name: EithonLibrary
main: net.eithon.plugin.eithonlibrary.EithonLibraryPlugin
version: ${project.version}
author: vanbrayne
depend: [Essentials]
softdepend: [PowerfulPerms, TitleManager]
description: A Minecraft plugin for the Eithon Java library which supports plugin development
commands:
  eithonlibrary:
    description: Should not need to be used?
    usage: /eithonfixes
    permission-message: You don't have <permission>
permissions:
  eithonlibrary.*:
    description: Gives access to all eithonlibrary commands
    default: op
